### ISSUE TITLE
Integrating with flask-admin

### ISSUE THREAD

**Issue by kepbod** [miguelgrinberg/Flask-PageDown#2]
I am new to flask, and I want to know how I integrate it with [flask-admin](https://github.com/mrjoes/flask-admin). Could you offer some examples? Thanks!

**Comment by duolaaa** [comment]
@miguelgrinberg  hi , i am now using flask-admin to build my blog background, i have seen the example of wysiwyg, but i want to use pagedown like [google pagedown](https://code.google.com/archive/p/pagedown) to edit my blog's articles. the markdown editor like stackoverflow or github . can i hava some way to achieve this function, can you give me some advice ? thank you very much, I greatly appreciate your can reply to me.
