### ISSUE TITLE
css conflict issue

### ISSUE THREAD

**Issue by abuakramGit** [miguelgrinberg/Flask-PageDown#32]
I pip installed pagedown but no formating bar is seen. After fiddeling around and disabling pico.css, the pagedown editor worked just fine. 
How can I resolve this css conflict

Thanks in advance

**Comment by miguelgrinberg** [comment]
This is a conflict between two JavaScript libraries and has nothing to do with this project, which is just a Flask integration. Unfortunately I do not know the answer to your question. Sorry.
